import { StyleSheet } from 'react-native';

import { colors } from '../theme/colors';
import { fonts } from '../theme/fonts';

export const addRestaurantStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FBF7F4',
  },
  keyboardView: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 24,
  },
  contentWithFooter: {
    paddingBottom: 104,
  },
  header: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#ECE4DE',
    borderRadius: 19,
    backgroundColor: colors.surface,
  },
  pressed: {
    opacity: 0.72,
    transform: [{ scale: 0.98 }],
  },
  secondaryPressed: {
    backgroundColor: '#FFF3EE',
  },
  headerTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 17,
  },
  headerSpacer: {
    width: 38,
    height: 38,
  },
  groupCard: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#EAE1DA',
    borderRadius: 16,
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: 6,
    shadowColor: '#3B241D',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.035,
    shadowRadius: 7,
    elevation: 1,
  },
  groupThumbnail: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#F4EEE9',
  },
  groupFallback: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#EEF4E7',
  },
  groupCopy: {
    flex: 1,
    gap: 1,
  },
  groupEyebrow: {
    color: colors.muted,
    fontFamily: fonts.medium,
    fontSize: 10,
  },
  groupName: {
    color: colors.primary,
    fontFamily: fonts.semiBold,
    fontSize: 14,
  },
  groupLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  groupLoadingText: {
    color: colors.muted,
    fontFamily: fonts.medium,
    fontSize: 11,
  },
  heading: {
    gap: 5,
    marginTop: 18,
    marginBottom: 14,
  },
  title: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 25,
    lineHeight: 30,
    letterSpacing: -0.55,
  },
  subtitle: {
    maxWidth: 430,
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 13,
    lineHeight: 18,
  },
  modeSelector: {
    flexDirection: 'row',
    gap: 3,
    borderWidth: 1,
    borderColor: '#EAE1DA',
    borderRadius: 15,
    backgroundColor: '#F0E8E3',
    padding: 3,
    marginBottom: 14,
  },
  modeButton: {
    flex: 1,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
  },
  activeModeButton: {
    backgroundColor: colors.primary,
    shadowColor: '#7A3B29',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  modeButtonText: {
    color: colors.muted,
    fontFamily: fonts.semiBold,
    fontSize: 12,
  },
  activeModeButtonText: {
    color: colors.white,
  },
  section: {
    gap: 12,
  },
  card: {
    gap: 13,
    borderWidth: 1,
    borderColor: '#EAE1DA',
    borderRadius: 18,
    backgroundColor: colors.surface,
    padding: 14,
    shadowColor: '#3B241D',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.025,
    shadowRadius: 6,
    elevation: 1,
  },
  sectionHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  sectionIcon: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: '#FFF0EA',
  },
  sectionHeadingCopy: {
    flex: 1,
    gap: 1,
  },
  sectionTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  sectionDescription: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 14,
  },
  formStack: {
    gap: 11,
  },
  inlineError: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 7,
    borderRadius: 12,
    backgroundColor: '#FFF0ED',
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  inlineErrorText: {
    flex: 1,
    color: colors.danger,
    fontFamily: fonts.medium,
    fontSize: 11,
    lineHeight: 16,
  },
  emptySearch: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#EDE5DE',
    borderRadius: 15,
    backgroundColor: colors.surface,
    padding: 12,
  },
  emptySearchCopy: {
    flex: 1,
    gap: 1,
  },
  emptyTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 13,
  },
  emptyText: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 14,
  },
  resultsSection: {
    gap: 8,
  },
  resultsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  resultsTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 17,
  },
  resultsCountBadge: {
    minWidth: 26,
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
    backgroundColor: '#EFE9E5',
    paddingHorizontal: 7,
  },
  resultsCount: {
    color: colors.muted,
    fontFamily: fonts.semiBold,
    fontSize: 10,
  },
  resultsHelp: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 14,
  },
  resultsList: {
    gap: 8,
  },
  attribution: {
    color: '#8B817C',
    fontFamily: fonts.regular,
    fontSize: 9,
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  manualShortcut: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    borderWidth: 1,
    borderColor: '#EAE1DA',
    borderRadius: 16,
    backgroundColor: colors.surface,
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  manualShortcutIcon: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: '#FFF0E7',
  },
  manualShortcutContent: {
    flex: 1,
    gap: 1,
  },
  manualShortcutTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 12,
  },
  manualShortcutText: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 9,
    lineHeight: 13,
  },
  manualShortcutButton: {
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 11,
    paddingHorizontal: 9,
  },
  manualShortcutButtonText: {
    color: colors.primary,
    fontFamily: fonts.semiBold,
    fontSize: 10,
  },
  selectedArea: {
    gap: 10,
  },
  selectedSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 13,
    backgroundColor: '#EEF5E7',
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  selectedSummaryCopy: {
    flex: 1,
    gap: 1,
  },
  selectedSummaryEyebrow: {
    color: '#5E7650',
    fontFamily: fonts.medium,
    fontSize: 9,
  },
  selectedSummaryName: {
    color: '#38532E',
    fontFamily: fonts.semiBold,
    fontSize: 12,
  },
  locationCard: {
    gap: 12,
    borderWidth: 1,
    borderColor: '#DDE5D2',
    borderRadius: 18,
    backgroundColor: '#FCFDF9',
    padding: 14,
  },
  twoColumns: {
    flexDirection: 'row',
    gap: 9,
  },
  column: {
    flex: 1,
    minWidth: 0,
  },
  locationPending: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    borderRadius: 12,
    backgroundColor: '#F2F6EC',
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  locationPendingText: {
    flex: 1,
    color: '#66725E',
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 14,
  },
  locationActionsRow: {
    flexDirection: 'row',
    gap: 7,
  },
  locationAction: {
    minHeight: 38,
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: '#DFCFC6',
    borderRadius: 11,
    backgroundColor: colors.surface,
    paddingHorizontal: 6,
  },
  locationActionDisabled: {
    opacity: 0.45,
  },
  locationActionPressed: {
    backgroundColor: '#FFF3EE',
  },
  locationActionText: {
    color: colors.primary,
    fontFamily: fonts.semiBold,
    fontSize: 9,
  },
  mapPreviewCard: {
    borderWidth: 1,
    borderColor: '#DCE5D0',
    borderRadius: 14,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  mapPreview: {
    width: '100%',
    height: 104,
  },
  locationConfirmed: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: '#F4F8EF',
  },
  locationConfirmedCopy: {
    flex: 1,
    gap: 1,
  },
  locationConfirmedTitle: {
    color: '#38532E',
    fontFamily: fonts.semiBold,
    fontSize: 11,
  },
  locationConfirmedText: {
    color: '#66725E',
    fontFamily: fonts.regular,
    fontSize: 9,
  },
  adjustButton: {
    minHeight: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 10,
    paddingHorizontal: 9,
  },
  adjustButtonText: {
    color: colors.primary,
    fontFamily: fonts.semiBold,
    fontSize: 9,
  },
  locationResults: {
    gap: 8,
  },
  locationResultsTitle: {
    color: colors.text,
    fontFamily: fonts.semiBold,
    fontSize: 12,
  },
  locationResultCard: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    borderWidth: 1,
    borderColor: '#E8E0D9',
    borderRadius: 13,
    backgroundColor: colors.surface,
    padding: 10,
  },
  locationResultIcon: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: '#FFF0EA',
  },
  locationResultCopy: {
    flex: 1,
    gap: 1,
  },
  locationResultLabel: {
    color: colors.text,
    fontFamily: fonts.medium,
    fontSize: 11,
    lineHeight: 15,
  },
  locationResultMeta: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 9,
  },
  notesInput: {
    minHeight: 70,
    paddingTop: 12,
  },
  requestErrorCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    borderWidth: 1,
    borderColor: '#F1C8BE',
    borderRadius: 13,
    backgroundColor: '#FFF1EE',
    padding: 11,
    marginTop: 12,
  },
  requestErrorText: {
    flex: 1,
    color: colors.danger,
    fontFamily: fonts.medium,
    fontSize: 11,
    lineHeight: 16,
  },
  footer: {
    gap: 6,
    borderTopWidth: 1,
    borderTopColor: '#E9E0D9',
    backgroundColor: 'rgba(251,247,244,0.98)',
    paddingHorizontal: 16,
    paddingTop: 9,
    paddingBottom: 10,
  },
  footerHint: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 9,
    lineHeight: 13,
    textAlign: 'center',
  },
  pickerSafeArea: {
    flex: 1,
    backgroundColor: '#FBF7F4',
  },
  pickerContainer: {
    flex: 1,
  },
  pickerHeader: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#EAE1DA',
    backgroundColor: '#FBF7F4',
  },
  pickerHeaderButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#EAE1DA',
    borderRadius: 19,
    backgroundColor: colors.surface,
  },
  pickerHeaderTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  pickerHeaderSpacer: {
    width: 38,
  },
  pickerMap: {
    flex: 1,
  },
  pickerPanel: {
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: '#E9E0D9',
    backgroundColor: colors.surface,
    paddingHorizontal: 16,
    paddingTop: 7,
    paddingBottom: 16,
  },
  pickerPanelHandle: {
    width: 40,
    height: 4,
    alignSelf: 'center',
    borderRadius: 2,
    backgroundColor: '#D7CCC5',
    marginBottom: 1,
  },
  pickerPanelTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 17,
  },
  pickerPanelText: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 11,
    lineHeight: 16,
  },
  pickerCoordinates: {
    color: '#8A817B',
    fontFamily: fonts.medium,
    fontSize: 9,
  },
});
