import { StyleSheet } from 'react-native';

import { colors } from '../theme/colors';
import { fonts } from '../theme/fonts';

export const addRestaurantStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FBF7F4',
  },
  keyboardView: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 26,
  },
  contentWithFooter: {
    paddingBottom: 108,
  },
  pressed: {
    opacity: 0.72,
  },
  header: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#ECE3DD',
    borderRadius: 19,
    backgroundColor: colors.surface,
  },
  headerTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 17,
  },
  headerSpacer: {
    width: 38,
    height: 38,
  },
  groupCard: {
    minHeight: 60,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#ECE3DC',
    borderRadius: 17,
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: 6,
    shadowColor: '#3B241D',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 7,
    elevation: 1,
  },
  groupThumbnail: {
    width: 42,
    height: 42,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#F4EEE9',
  },
  groupImage: {
    width: '100%',
    height: '100%',
  },
  groupFallback: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#EFF4E8',
  },
  groupCopy: {
    flex: 1,
    gap: 1,
  },
  groupEyebrow: {
    color: colors.muted,
    fontFamily: fonts.medium,
    fontSize: 10,
  },
  groupName: {
    color: colors.primary,
    fontFamily: fonts.semiBold,
    fontSize: 14,
  },
  heading: {
    gap: 5,
    marginTop: 18,
    marginBottom: 14,
  },
  title: {
    maxWidth: 420,
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 25,
    lineHeight: 30,
    letterSpacing: -0.55,
  },
  subtitle: {
    maxWidth: 440,
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 17,
  },
  modeSelector: {
    flexDirection: 'row',
    gap: 3,
    borderWidth: 1,
    borderColor: '#ECE3DD',
    borderRadius: 15,
    backgroundColor: '#F1E9E4',
    padding: 3,
    marginBottom: 14,
  },
  modeButton: {
    flex: 1,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
  },
  activeModeButton: {
    backgroundColor: colors.primary,
    shadowColor: '#7A3B29',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.13,
    shadowRadius: 4,
    elevation: 2,
  },
  modeButtonText: {
    color: colors.muted,
    fontFamily: fonts.semiBold,
    fontSize: 12,
  },
  activeModeButtonText: {
    color: colors.white,
  },
  section: {
    gap: 12,
  },
  sectionCard: {
    gap: 13,
    borderWidth: 1,
    borderColor: '#EDE4DD',
    borderRadius: 18,
    backgroundColor: colors.surface,
    padding: 14,
    shadowColor: '#3B241D',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.025,
    shadowRadius: 6,
    elevation: 1,
  },
  sectionHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  sectionIcon: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: '#FFF0EA',
  },
  sectionHeadingCopy: {
    flex: 1,
    gap: 1,
  },
  sectionTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  sectionDescription: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 14,
  },
  photoPicker: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#E8DED7',
    borderRadius: 15,
    backgroundColor: '#FFFCFA',
    padding: 9,
  },
  photoPickerPressed: {
    backgroundColor: '#FFF7F2',
  },
  photoPreview: {
    width: 54,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: '#F9E8E0',
    overflow: 'hidden',
  },
  photoImage: {
    width: '100%',
    height: '100%',
  },
  photoCopy: {
    flex: 1,
    gap: 2,
  },
  photoTitle: {
    color: colors.text,
    fontFamily: fonts.semiBold,
    fontSize: 13,
  },
  photoSubtitle: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 14,
  },
  photoAction: {
    minHeight: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: '#FFF0EA',
    paddingHorizontal: 9,
  },
  photoActionText: {
    color: colors.primary,
    fontFamily: fonts.semiBold,
    fontSize: 10,
  },
  inlineError: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 7,
    borderRadius: 12,
    backgroundColor: '#FFF0ED',
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  inlineErrorText: {
    flex: 1,
    color: colors.danger,
    fontFamily: fonts.medium,
    fontSize: 11,
    lineHeight: 16,
  },
  emptySearch: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    borderWidth: 1,
    borderColor: '#EDE5DE',
    borderRadius: 16,
    backgroundColor: colors.surface,
    padding: 13,
  },
  emptySearchCopy: {
    flex: 1,
    gap: 2,
  },
  emptyTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 13,
  },
  emptyText: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 14,
  },
  resultsSection: {
    gap: 9,
  },
  resultsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  resultsTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 17,
  },
  resultsCount: {
    minWidth: 26,
    height: 26,
    color: colors.muted,
    fontFamily: fonts.semiBold,
    fontSize: 10,
    lineHeight: 26,
    textAlign: 'center',
    borderRadius: 13,
    backgroundColor: '#F1EBE7',
  },
  resultsList: {
    gap: 8,
  },
  attribution: {
    color: '#8B817C',
    fontFamily: fonts.regular,
    fontSize: 9,
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  manualShortcut: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    borderWidth: 1,
    borderColor: '#EDE4DE',
    borderRadius: 16,
    backgroundColor: colors.surface,
    padding: 11,
  },
  manualShortcutContent: {
    flex: 1,
    gap: 1,
  },
  manualShortcutTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 12,
  },
  manualShortcutText: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 9,
    lineHeight: 13,
  },
  manualShortcutButton: {
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 11,
    paddingHorizontal: 9,
  },
  manualShortcutButtonText: {
    color: colors.primary,
    fontFamily: fonts.semiBold,
    fontSize: 10,
  },
  afterSelection: {
    gap: 12,
  },
  selectedSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    borderRadius: 14,
    backgroundColor: '#F1F6EA',
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  selectedSummaryCopy: {
    flex: 1,
    gap: 1,
  },
  selectedSummaryEyebrow: {
    color: '#5E7650',
    fontFamily: fonts.medium,
    fontSize: 9,
  },
  selectedSummaryName: {
    color: '#38532E',
    fontFamily: fonts.semiBold,
    fontSize: 12,
  },
  locationCard: {
    gap: 13,
    borderWidth: 1,
    borderColor: '#E5EAD9',
    borderRadius: 18,
    backgroundColor: '#FCFDF9',
    padding: 14,
  },
  inlineFields: {
    flexDirection: 'row',
    gap: 10,
  },
  inlineField: {
    flex: 1,
  },
  locationEmpty: {
    gap: 3,
    borderRadius: 13,
    backgroundColor: '#F3F6ED',
    paddingHorizontal: 11,
    paddingVertical: 10,
  },
  locationEmptyTitle: {
    color: '#46543C',
    fontFamily: fonts.semiBold,
    fontSize: 11,
  },
  locationEmptyText: {
    color: '#6C7764',
    fontFamily: fonts.regular,
    fontSize: 9,
    lineHeight: 13,
  },
  locationActions: {
    flexDirection: 'row',
    gap: 7,
  },
  locationAction: {
    minHeight: 38,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    borderWidth: 1,
    borderColor: '#E3D7D0',
    borderRadius: 11,
    backgroundColor: colors.surface,
    paddingHorizontal: 7,
  },
  locationActionDisabled: {
    opacity: 0.45,
  },
  locationActionPressed: {
    backgroundColor: '#FFF3EE',
  },
  locationActionText: {
    color: colors.primary,
    fontFamily: fonts.semiBold,
    fontSize: 9,
  },
  locationResults: {
    gap: 8,
  },
  locationResultsTitle: {
    color: colors.text,
    fontFamily: fonts.semiBold,
    fontSize: 12,
  },
  locationResultCard: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#E9E1DA',
    borderRadius: 13,
    backgroundColor: colors.surface,
    padding: 10,
  },
  locationResultLabel: {
    flex: 1,
    color: colors.text,
    fontFamily: fonts.medium,
    fontSize: 11,
    lineHeight: 15,
  },
  mapPreviewCard: {
    borderWidth: 1,
    borderColor: '#DFE7D2',
    borderRadius: 14,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  mapPreview: {
    width: '100%',
    height: 104,
  },
  mapConfirmed: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    backgroundColor: '#F1F6EA',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  mapConfirmedText: {
    flex: 1,
    color: '#4D6540',
    fontFamily: fonts.medium,
    fontSize: 10,
    lineHeight: 14,
  },
  notesCard: {
    gap: 12,
    borderWidth: 1,
    borderColor: '#EDE4DD',
    borderRadius: 18,
    backgroundColor: colors.surface,
    padding: 14,
  },
  notesInput: {
    minHeight: 76,
    paddingTop: 12,
  },
  requestErrorCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    borderWidth: 1,
    borderColor: '#F1C8BE',
    borderRadius: 13,
    backgroundColor: '#FFF1EE',
    padding: 11,
    marginTop: 12,
  },
  requestErrorText: {
    flex: 1,
    color: colors.danger,
    fontFamily: fonts.medium,
    fontSize: 11,
    lineHeight: 16,
  },
  stickyFooter: {
    borderTopWidth: 1,
    borderTopColor: '#EDE4DE',
    backgroundColor: 'rgba(251,247,244,0.98)',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 12,
  },
  pickerSafeArea: {
    flex: 1,
    backgroundColor: '#FBF7F4',
  },
  pickerContainer: {
    flex: 1,
  },
  pickerHeader: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#ECE3DD',
    backgroundColor: '#FBF7F4',
  },
  pickerHeaderButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#ECE3DD',
    borderRadius: 19,
    backgroundColor: colors.surface,
  },
  pickerHeaderTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  pickerHeaderSpacer: {
    width: 38,
  },
  pickerMap: {
    flex: 1,
  },
  pickerPanel: {
    gap: 9,
    borderTopWidth: 1,
    borderTopColor: '#E9E0D9',
    backgroundColor: colors.surface,
    paddingHorizontal: 17,
    paddingTop: 8,
    paddingBottom: 17,
  },
  pickerPanelHandle: {
    width: 40,
    height: 4,
    alignSelf: 'center',
    borderRadius: 2,
    backgroundColor: '#D7CCC5',
  },
  pickerPanelTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 17,
  },
  pickerPanelText: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 11,
    lineHeight: 16,
  },
  pickerCoordinates: {
    color: '#8A817B',
    fontFamily: fonts.medium,
    fontSize: 9,
  },
});
