import { StyleSheet } from 'react-native';

import { colors } from '../theme/colors';
import { fonts } from '../theme/fonts';

export const addRestaurantStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FBF7F4',
  },
  keyboardView: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 40,
  },
  header: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerButton: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#EEE5DE',
    borderRadius: 21,
    backgroundColor: colors.surface,
    shadowColor: '#3B241D',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 7,
    elevation: 2,
  },
  headerButtonPressed: {
    opacity: 0.72,
    transform: [{ scale: 0.97 }],
  },
  headerTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 18,
  },
  headerSpacer: {
    width: 42,
    height: 42,
  },
  groupCard: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    borderWidth: 1,
    borderColor: '#ECE3DC',
    borderRadius: 18,
    backgroundColor: colors.surface,
    paddingHorizontal: 11,
    paddingVertical: 9,
    marginTop: 10,
    shadowColor: '#3B241D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.045,
    shadowRadius: 10,
    elevation: 2,
  },
  groupCardPressed: {
    backgroundColor: '#FFF9F6',
  },
  groupThumbnail: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: '#F4EEE9',
    overflow: 'hidden',
  },
  groupImage: {
    width: '100%',
    height: '100%',
  },
  groupFallback: {
    width: 46,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: '#F1F5E9',
  },
  groupCopy: {
    flex: 1,
    gap: 2,
  },
  groupEyebrow: {
    color: colors.muted,
    fontFamily: fonts.medium,
    fontSize: 11,
  },
  groupName: {
    color: colors.primary,
    fontFamily: fonts.semiBold,
    fontSize: 15,
  },
  groupLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  groupLoadingText: {
    color: colors.muted,
    fontFamily: fonts.medium,
    fontSize: 12,
  },
  heading: {
    gap: 7,
    marginTop: 24,
    marginBottom: 18,
  },
  title: {
    maxWidth: 420,
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 29,
    lineHeight: 34,
    letterSpacing: -0.65,
  },
  subtitle: {
    maxWidth: 440,
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 14,
    lineHeight: 20,
  },
  modeSelector: {
    flexDirection: 'row',
    gap: 4,
    borderWidth: 1,
    borderColor: '#ECE3DD',
    borderRadius: 17,
    backgroundColor: '#F2EAE5',
    padding: 4,
    marginBottom: 18,
  },
  modeButton: {
    flex: 1,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
  },
  activeModeButton: {
    backgroundColor: colors.primary,
    shadowColor: '#7A3B29',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 2,
  },
  modeButtonText: {
    color: colors.muted,
    fontFamily: fonts.semiBold,
    fontSize: 13,
  },
  activeModeButtonText: {
    color: colors.white,
  },
  section: {
    gap: 16,
  },
  sectionCard: {
    gap: 16,
    borderWidth: 1,
    borderColor: '#EDE4DD',
    borderRadius: 20,
    backgroundColor: colors.surface,
    padding: 16,
    shadowColor: '#3B241D',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.035,
    shadowRadius: 8,
    elevation: 1,
  },
  sectionHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sectionIcon: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
    backgroundColor: '#FFF0EA',
  },
  greenSectionIcon: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
    backgroundColor: '#EFF4E8',
  },
  sectionHeadingCopy: {
    flex: 1,
    gap: 2,
  },
  sectionTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  sectionDescription: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 11,
    lineHeight: 16,
  },
  formStack: {
    gap: 14,
  },
  inlineError: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    borderRadius: 13,
    backgroundColor: '#FFF0ED',
    paddingHorizontal: 11,
    paddingVertical: 10,
  },
  inlineErrorText: {
    flex: 1,
    color: colors.danger,
    fontFamily: fonts.medium,
    fontSize: 12,
    lineHeight: 17,
  },
  emptySearch: {
    alignItems: 'center',
    gap: 7,
    borderWidth: 1,
    borderColor: '#EDE5DE',
    borderRadius: 18,
    backgroundColor: colors.surface,
    paddingHorizontal: 20,
    paddingVertical: 22,
  },
  emptySearchIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: '#FFF0EA',
  },
  emptyTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  emptyText: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },
  resultsSection: {
    gap: 10,
  },
  resultsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  resultsTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 19,
  },
  resultsCountBadge: {
    minWidth: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: '#F1EBE7',
    paddingHorizontal: 8,
  },
  resultsCount: {
    color: colors.muted,
    fontFamily: fonts.semiBold,
    fontSize: 11,
  },
  resultsHelp: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 11,
    lineHeight: 16,
  },
  resultsList: {
    gap: 9,
  },
  attribution: {
    color: '#8B817C',
    fontFamily: fonts.regular,
    fontSize: 9,
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  manualShortcut: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#EDE4DE',
    borderRadius: 17,
    backgroundColor: colors.surface,
    padding: 12,
  },
  manualShortcutIcon: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
    backgroundColor: '#FFF0E7',
  },
  manualShortcutContent: {
    flex: 1,
    gap: 1,
  },
  manualShortcutTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 13,
  },
  manualShortcutText: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 15,
  },
  manualShortcutButton: {
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 12,
    paddingHorizontal: 10,
  },
  manualShortcutButtonPressed: {
    backgroundColor: '#FFF0EA',
  },
  manualShortcutButtonText: {
    color: colors.primary,
    fontFamily: fonts.semiBold,
    fontSize: 11,
  },
  detailsCard: {
    borderWidth: 1,
    borderColor: '#EDE4DD',
    borderRadius: 20,
    backgroundColor: colors.surface,
    padding: 14,
  },
  detailsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  detailsHeaderContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  detailsBody: {
    gap: 14,
    paddingTop: 16,
  },
  locationCard: {
    gap: 14,
    borderWidth: 1,
    borderColor: '#E6EBD8',
    borderRadius: 20,
    backgroundColor: '#FCFDF9',
    padding: 16,
  },
  locationEmpty: {
    gap: 4,
    borderRadius: 14,
    backgroundColor: '#F4F7EE',
    paddingHorizontal: 13,
    paddingVertical: 12,
  },
  locationEmptyTitle: {
    color: '#46543C',
    fontFamily: fonts.semiBold,
    fontSize: 13,
  },
  locationEmptyText: {
    color: '#6C7764',
    fontFamily: fonts.regular,
    fontSize: 11,
    lineHeight: 16,
  },
  locationActions: {
    gap: 9,
  },
  locationPrimaryAction: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 14,
    backgroundColor: colors.primary,
    paddingHorizontal: 14,
  },
  locationPrimaryActionDisabled: {
    opacity: 0.5,
  },
  locationActionPressed: {
    backgroundColor: colors.primaryPressed,
  },
  locationPrimaryActionText: {
    color: colors.white,
    fontFamily: fonts.semiBold,
    fontSize: 13,
  },
  locationSecondaryRow: {
    flexDirection: 'row',
    gap: 9,
  },
  locationSecondaryAction: {
    minHeight: 42,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#E3D7D0',
    borderRadius: 13,
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
  },
  locationSecondaryActionPressed: {
    backgroundColor: '#FFF3EE',
  },
  locationSecondaryActionText: {
    color: colors.primary,
    fontFamily: fonts.semiBold,
    fontSize: 11,
  },
  locationResults: {
    gap: 9,
  },
  locationResultsTitle: {
    color: colors.text,
    fontFamily: fonts.semiBold,
    fontSize: 13,
  },
  locationResultCard: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#E9E1DA',
    borderRadius: 14,
    backgroundColor: colors.surface,
    padding: 11,
  },
  locationResultCardPressed: {
    backgroundColor: '#FFF7F3',
  },
  locationResultIcon: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: '#FFF0EA',
  },
  locationResultCopy: {
    flex: 1,
    gap: 2,
  },
  locationResultLabel: {
    color: colors.text,
    fontFamily: fonts.medium,
    fontSize: 12,
    lineHeight: 16,
  },
  locationResultMeta: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 9,
  },
  mapPreviewCard: {
    borderWidth: 1,
    borderColor: '#DFE7D2',
    borderRadius: 16,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  mapPreview: {
    width: '100%',
    height: 138,
  },
  mapPreviewHeader: {
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  mapPreviewIcon: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: '#EEF5E7',
  },
  mapPreviewCopy: {
    flex: 1,
    gap: 1,
  },
  mapPreviewTitle: {
    color: '#38532E',
    fontFamily: fonts.semiBold,
    fontSize: 12,
  },
  mapPreviewText: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 14,
  },
  mapPreviewEdit: {
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 11,
    paddingHorizontal: 10,
  },
  mapPreviewEditText: {
    color: colors.primary,
    fontFamily: fonts.semiBold,
    fontSize: 10,
  },
  notesCard: {
    gap: 14,
    borderWidth: 1,
    borderColor: '#EDE4DD',
    borderRadius: 20,
    backgroundColor: colors.surface,
    padding: 16,
  },
  notesHeader: {
    gap: 3,
  },
  notesTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 17,
  },
  notesDescription: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 11,
    lineHeight: 16,
  },
  notesInput: {
    minHeight: 88,
    paddingTop: 14,
  },
  saveSection: {
    gap: 14,
  },
  saveHint: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 11,
    lineHeight: 16,
    textAlign: 'center',
    paddingHorizontal: 8,
  },
  selectedSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    borderRadius: 15,
    backgroundColor: '#F1F6EA',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  selectedSummaryCopy: {
    flex: 1,
    gap: 1,
  },
  selectedSummaryEyebrow: {
    color: '#5E7650',
    fontFamily: fonts.medium,
    fontSize: 10,
  },
  selectedSummaryName: {
    color: '#38532E',
    fontFamily: fonts.semiBold,
    fontSize: 13,
  },
  requestErrorCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    borderWidth: 1,
    borderColor: '#F1C8BE',
    borderRadius: 14,
    backgroundColor: '#FFF1EE',
    padding: 12,
  },
  requestErrorText: {
    flex: 1,
    color: colors.danger,
    fontFamily: fonts.medium,
    fontSize: 12,
    lineHeight: 17,
  },
  pickerSafeArea: {
    flex: 1,
    backgroundColor: '#FBF7F4',
  },
  pickerContainer: {
    flex: 1,
  },
  pickerHeader: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#ECE3DD',
    backgroundColor: '#FBF7F4',
  },
  pickerHeaderButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#ECE3DD',
    borderRadius: 20,
    backgroundColor: colors.surface,
  },
  pickerHeaderTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 17,
  },
  pickerHeaderSpacer: {
    width: 40,
  },
  pickerMap: {
    flex: 1,
  },
  pickerPanel: {
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: '#E9E0D9',
    backgroundColor: colors.surface,
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 18,
  },
  pickerPanelHandle: {
    width: 42,
    height: 4,
    alignSelf: 'center',
    borderRadius: 2,
    backgroundColor: '#D7CCC5',
    marginBottom: 2,
  },
  pickerPanelTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 18,
  },
  pickerPanelText: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 17,
  },
  pickerCoordinates: {
    color: '#8A817B',
    fontFamily: fonts.medium,
    fontSize: 10,
    marginBottom: 2,
  },
});
