import { StyleSheet } from 'react-native';

import { colors } from '../theme/colors';
import { fonts } from '../theme/fonts';
import { shadows } from '../theme/layout';

export const addHubScreenStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    flexGrow: 1,
    paddingBottom: 108,
  },
  header: {
    position: 'relative',
    overflow: 'hidden',
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
  },
  headerTopRow: {
    zIndex: 3,
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 20,
  },
  closeButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: 'rgba(255, 235, 224, 0.28)',
  },
  headerSpacer: {
    width: 40,
    height: 40,
  },
  headerTitle: {
    color: colors.white,
    fontFamily: fonts.semiBold,
    fontSize: 20,
    lineHeight: 25,
    letterSpacing: -0.35,
  },
  heroPlus: {
    position: 'absolute',
    zIndex: 1,
    right: 21,
    color: 'rgba(255, 206, 181, 0.76)',
    fontFamily: fonts.regular,
    fontSize: 32,
    lineHeight: 35,
  },
  headerIllustration: {
    position: 'absolute',
    right: -50,
    bottom: -78,
    width: 180,
    height: 180,
    opacity: 0.7,
  },
  body: {
    paddingTop: 38,
    paddingHorizontal: 27,
  },
  intro: {
    gap: 4,
  },
  title: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 28,
    lineHeight: 36,
    letterSpacing: -0.95,
  },
  subtitle: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 14.5,
    lineHeight: 21,
    letterSpacing: -0.15,
  },
  searchSection: {
    marginTop: 24,
  },
  sectionLabel: {
    color: '#BC4029',
    fontFamily: fonts.semiBold,
    fontSize: 11.5,
    lineHeight: 16,
    letterSpacing: 1.45,
  },
  searchCard: {
    height: 68,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
    marginTop: 11,
    paddingLeft: 18,
    paddingRight: 14,
    borderWidth: 1,
    borderColor: '#DED2CA',
    borderRadius: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.86)',
    ...shadows.card,
  },
  searchPlaceholder: {
    flex: 1,
    minWidth: 0,
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 14.5,
    lineHeight: 20,
    letterSpacing: -0.2,
  },
  searchArrow: {
    width: 40,
    height: 40,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: '#C94129',
  },
  searchHelper: {
    marginTop: 11,
    marginLeft: 4,
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 13.5,
    lineHeight: 19,
    letterSpacing: -0.15,
  },
  otherSection: {
    marginTop: 38,
  },
  groupedCard: {
    marginTop: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E0D5CE',
    borderRadius: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
    ...shadows.card,
  },
  singleCard: {
    height: 84,
    marginTop: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E0D5CE',
    borderRadius: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
    ...shadows.card,
  },
  actionRow: {
    minHeight: 84,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
    paddingHorizontal: 14,
  },
  actionIcon: {
    width: 56,
    height: 56,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
  },
  actionIconOlive: {
    backgroundColor: '#EEF1E2',
  },
  actionIconTerracotta: {
    backgroundColor: '#F9E2DA',
  },
  actionIconNeutral: {
    backgroundColor: '#F4F0E7',
  },
  actionCopy: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  actionTitle: {
    color: colors.text,
    fontFamily: fonts.semiBold,
    fontSize: 16,
    lineHeight: 21,
    letterSpacing: -0.35,
  },
  actionSubtitle: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: -0.15,
  },
  divider: {
    height: 1,
    marginHorizontal: 13,
    backgroundColor: '#E8DFDA',
  },
  spaceSection: {
    marginTop: 38,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.988 }],
  },
});
