import { StyleSheet } from 'react-native';

import { colors } from '../theme/colors';
import { fonts } from '../theme/fonts';
import { shadows } from '../theme/layout';

export const addHubScreenStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    flexGrow: 1,
    paddingBottom: 108,
  },
  header: {
    position: 'relative',
    overflow: 'hidden',
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
  },
  headerTopRow: {
    zIndex: 3,
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 20,
  },
  closeButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: 'rgba(255, 235, 224, 0.22)',
  },
  headerSpacer: {
    width: 40,
    height: 40,
  },
  headerTitle: {
    color: colors.white,
    fontFamily: fonts.semiBold,
    fontSize: 20,
    lineHeight: 25,
    letterSpacing: -0.35,
  },
  heroCopy: {
    zIndex: 2,
    gap: 7,
    marginTop: 27,
    marginHorizontal: 26,
  },
  eyebrow: {
    color: '#FFE3D5',
    fontFamily: fonts.semiBold,
    fontSize: 11.5,
    lineHeight: 15,
    letterSpacing: 1.15,
  },
  title: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 31,
    lineHeight: 39,
    letterSpacing: -1.15,
  },
  subtitle: {
    color: '#FFE7DA',
    fontFamily: fonts.regular,
    fontSize: 14.5,
    lineHeight: 21,
    letterSpacing: -0.15,
  },
  heroPlus: {
    position: 'absolute',
    zIndex: 1,
    right: 26,
    color: 'rgba(255, 206, 181, 0.66)',
    fontFamily: fonts.regular,
    fontSize: 36,
    lineHeight: 39,
  },
  headerIllustration: {
    position: 'absolute',
    right: -54,
    bottom: -42,
    width: 184,
    height: 184,
    opacity: 0.7,
  },
  body: {
    paddingTop: 23,
    paddingHorizontal: 26,
  },
  featuredList: {
    gap: 14,
  },
  featuredAction: {
    height: 118,
    overflow: 'hidden',
    borderRadius: 16,
  },
  featuredActionSurface: {
    position: 'relative',
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    overflow: 'hidden',
    paddingHorizontal: 20,
    borderWidth: 1,
    borderRadius: 16,
  },
  featuredActionTerracotta: {
    borderColor: '#C54028',
  },
  featuredActionOlive: {
    borderColor: '#9BA774',
  },
  featuredDecoration: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 124,
    overflow: 'hidden',
  },
  featuredArcOuter: {
    position: 'absolute',
    right: -65,
    bottom: -79,
    width: 178,
    height: 178,
    borderWidth: 1,
    borderColor: 'rgba(255, 196, 170, 0.35)',
    borderRadius: 89,
  },
  featuredArcInner: {
    position: 'absolute',
    right: -47,
    bottom: -62,
    width: 138,
    height: 138,
    borderWidth: 1,
    borderColor: 'rgba(255, 196, 170, 0.28)',
    borderRadius: 69,
  },
  featuredIcon: {
    zIndex: 1,
    width: 64,
    height: 66,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
  },
  featuredIconTerracotta: {
    backgroundColor: '#FFF9F4',
  },
  featuredIconOlive: {
    backgroundColor: 'rgba(255, 255, 255, 0.86)',
  },
  featuredCopy: {
    zIndex: 1,
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  featuredTitle: {
    color: colors.text,
    fontFamily: fonts.semiBold,
    fontSize: 20,
    lineHeight: 25,
    letterSpacing: -0.65,
  },
  featuredTitleLight: {
    color: colors.white,
  },
  featuredSubtitle: {
    maxWidth: 210,
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 14,
    lineHeight: 19,
    letterSpacing: -0.2,
  },
  featuredSubtitleLight: {
    color: '#FFE6D9',
  },
  featuredArrow: {
    zIndex: 1,
    width: 41,
    height: 41,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 21,
  },
  featuredArrowTerracotta: {
    backgroundColor: '#FFF9F4',
  },
  featuredArrowOlive: {
    backgroundColor: 'rgba(255, 255, 255, 0.83)',
  },
  section: {
    marginTop: 28,
  },
  sectionHeading: {
    gap: 3,
  },
  sectionTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 20,
    lineHeight: 26,
    letterSpacing: -0.6,
  },
  sectionCaption: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 14,
    lineHeight: 19,
  },
  secondaryList: {
    gap: 10,
    marginTop: 14,
  },
  secondaryAction: {
    height: 74,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: 13,
    borderWidth: 1,
    borderColor: '#E4D7CF',
    borderRadius: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.84)',
    ...shadows.card,
  },
  secondaryIcon: {
    width: 48,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
  },
  secondaryIconTerracotta: {
    backgroundColor: '#F6DDD5',
  },
  secondaryIconOlive: {
    backgroundColor: '#EBEEDF',
  },
  secondaryCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  secondaryTitle: {
    color: colors.text,
    fontFamily: fonts.semiBold,
    fontSize: 15.5,
    lineHeight: 20,
    letterSpacing: -0.3,
  },
  secondarySubtitle: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 12.5,
    lineHeight: 17,
    letterSpacing: -0.12,
  },
  tipCard: {
    minHeight: 65,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginTop: 12,
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#E8C58E',
    borderRadius: 13,
  },
  tipIcon: {
    width: 45,
    height: 48,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.58)',
  },
  tipCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  tipTitle: {
    color: colors.text,
    fontFamily: fonts.semiBold,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: -0.25,
  },
  tipText: {
    color: colors.mutedStrong,
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: -0.15,
  },
  pressed: {
    opacity: 0.84,
    transform: [{ scale: 0.988 }],
  },
});
