import { StyleSheet } from 'react-native';

import { colors } from '../theme/colors';
import { fonts } from '../theme/fonts';

export const groupCardStyles = StyleSheet.create({
  card: {
    width: 246,
    height: 170,
    overflow: 'hidden',
    borderRadius: 22,
    backgroundColor: '#D7CEC8',
  },
  image: { flex: 1, overflow: 'hidden', borderRadius: 22 },
  imageRadius: { borderRadius: 22 },
  overlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(30,22,18,0.38)',
  },
  fallbackIcon: { position: 'absolute', top: 52, right: 20 },
  privacyPill: {
    position: 'absolute',
    top: 12,
    left: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.94)',
  },
  privacyText: { color: '#5C7842', fontSize: 8, fontFamily: fonts.semiBold },
  bottomContent: {
    position: 'absolute',
    right: 14,
    bottom: 13,
    left: 14,
    gap: 5,
  },
  title: {
    color: colors.white,
    fontSize: 17,
    fontFamily: fonts.bold,
    letterSpacing: -0.15,
  },
  locationRow: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  locationText: { flex: 1, color: colors.white, fontSize: 10, fontFamily: fonts.medium },
  avatarStack: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 1,
  },
  avatar: {
    width: 27,
    height: 27,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 1.25,
    borderColor: colors.white,
    borderRadius: 14,
    backgroundColor: '#F4DFD5',
  },
  avatarImage: { width: '100%', height: '100%' },
  avatarInitial: { color: colors.primary, fontSize: 9, fontFamily: fonts.bold },
  avatarOverlap: { marginLeft: -7 },
  moreAvatar: {
    width: 27,
    height: 27,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.25,
    borderColor: colors.white,
    borderRadius: 14,
    backgroundColor: 'rgba(65,55,49,0.72)',
  },
  moreAvatarText: { color: colors.white, fontSize: 8, fontFamily: fonts.bold },
  emptyAvatar: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
    borderWidth: 1.25,
    borderColor: colors.white,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  pressed: { opacity: 0.82, transform: [{ scale: 0.99 }] },
});
