import { StyleSheet } from 'react-native';

export const refinedHomeStyles = StyleSheet.create({
  safeArea: {},
  content: {
    gap: 25,
  },
  brand: {},
  topActions: {},
  avatarButton: {},
  hero: {},
  title: {},
  subtitle: {},
  searchBar: {},
  searchText: {},
  quickActions: {},
  section: {},
  sectionHeader: {},
  sectionTitle: {},
  sectionAction: {},
  sectionActionText: {},
  groupGrid: {},
  activityList: {},
  emptyCard: {},
  emptyIcon: {},
  emptyTitle: {},
  emptySubtitle: {},
  loadingCard: {},
  loadingText: {},
});
