import { Platform, StyleSheet } from 'react-native';

import { colors } from '../theme/colors';
import { fonts } from '../theme/fonts';
import { shadows } from '../theme/layout';

export const homeBrandFont = Platform.select({
  ios: 'Georgia-Bold',
  android: 'serif',
  default: 'serif',
});

export const homeStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FCF9F7',
  },
  content: {
    flexGrow: 1,
    backgroundColor: '#FCF9F7',
  },
  header: {
    width: '100%',
  },
  heroBackground: {
    position: 'relative',
    overflow: 'hidden',
    paddingHorizontal: 20,
    borderBottomLeftRadius: 17,
    borderBottomRightRadius: 17,
  },
  topBar: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brand: {
    color: '#FFF9F4',
    fontFamily: homeBrandFont,
    fontSize: 35,
    fontWeight: '800',
    lineHeight: 42,
    letterSpacing: -1.1,
  },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatarButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderRadius: 18,
    backgroundColor: '#FFF9F3',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarInitial: {
    color: '#C4492D',
    fontFamily: fonts.semiBold,
    fontSize: 14,
  },
  heroCopy: {
    zIndex: 2,
    marginTop: 16,
  },
  greeting: {
    color: '#F8DCCC',
    fontFamily: fonts.medium,
    fontSize: 14,
    lineHeight: 19,
  },
  title: {
    marginTop: 5,
    color: '#FFFFFF',
    fontFamily: fonts.bold,
    fontSize: 28,
    lineHeight: 35,
    letterSpacing: -0.85,
  },
  subtitle: {
    marginTop: 3,
    color: '#FFE6D7',
    fontFamily: fonts.regular,
    fontSize: 13,
    lineHeight: 18,
  },
  illustration: {
    position: 'absolute',
    right: -51,
    bottom: -40,
    width: 176,
    height: 180,
  },
  headerControls: {
    zIndex: 4,
    marginTop: -28,
    paddingHorizontal: 20,
  },
  searchBar: {
    height: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    paddingHorizontal: 17,
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    shadowColor: '#5E3A2D',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.17,
    shadowRadius: 12,
    elevation: 7,
  },
  searchText: {
    flex: 1,
    color: '#766F6B',
    fontFamily: fonts.regular,
    fontSize: 14,
    lineHeight: 19,
  },
  quickActions: {
    flexDirection: 'row',
    gap: 13,
    marginTop: 14,
    paddingHorizontal: 3,
  },
  dashboard: {
    gap: 14,
    paddingHorizontal: 22,
    paddingTop: 12,
  },
  section: {
    gap: 5,
  },
  sectionHeader: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionTitle: {
    color: '#29221F',
    fontFamily: fonts.bold,
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: -0.35,
  },
  sectionAction: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingLeft: 8,
  },
  sectionActionText: {
    color: colors.olive,
    fontFamily: fonts.semiBold,
    fontSize: 12,
    lineHeight: 16,
  },
  groupGrid: {
    gap: 12,
  },
  activityList: {
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E2D7D1',
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
  },
  emptyCard: {
    minHeight: 84,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 13,
    borderWidth: 1,
    borderColor: '#E2D7D1',
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
  },
  emptyIcon: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: colors.primarySoft,
  },
  emptyCopy: {
    flex: 1,
    gap: 3,
  },
  emptyTitle: {
    color: colors.text,
    fontFamily: fonts.semiBold,
    fontSize: 13,
  },
  emptySubtitle: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 14,
  },
  loadingCard: {
    minHeight: 188,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginHorizontal: 22,
    marginTop: 22,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    backgroundColor: colors.surface,
    ...shadows.card,
  },
  loadingText: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 12,
  },
  errorCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginHorizontal: 22,
    marginTop: 22,
    padding: 15,
    borderWidth: 1,
    borderColor: '#F0C7BF',
    borderRadius: 18,
    backgroundColor: colors.dangerSoft,
  },
  errorIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: '#FBE2DD',
  },
  errorCopy: {
    flex: 1,
    gap: 5,
  },
  errorTitle: {
    color: colors.danger,
    fontFamily: fonts.semiBold,
    fontSize: 13,
  },
  errorText: {
    color: colors.mutedStrong,
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 15,
  },
  retryText: {
    marginTop: 3,
    color: colors.primary,
    fontFamily: fonts.semiBold,
    fontSize: 10,
  },
  pressed: {
    opacity: 0.78,
  },
});
