import { Platform, StyleSheet } from 'react-native';

import { colors } from '../theme/colors';
import { fonts } from '../theme/fonts';
import { shadows } from '../theme/layout';

export const homeBrandFont = Platform.select({
  ios: 'Georgia-Bold',
  android: 'serif',
  default: 'serif',
});

const illustrationLine = 'rgba(255, 224, 204, 0.54)';

export const homeStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FCF9F7',
  },
  content: {
    flexGrow: 1,
    backgroundColor: '#FCF9F7',
  },
  header: {
    width: '100%',
  },
  heroBackground: {
    position: 'relative',
    overflow: 'hidden',
    paddingHorizontal: 20,
    borderBottomLeftRadius: 17,
    borderBottomRightRadius: 17,
  },
  topBar: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brand: {
    color: '#FFF9F4',
    fontFamily: homeBrandFont,
    fontSize: 35,
    fontWeight: '800',
    lineHeight: 42,
    letterSpacing: -1.1,
  },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatarButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderRadius: 18,
    backgroundColor: '#FFF9F3',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarInitial: {
    color: '#C4492D',
    fontFamily: fonts.semiBold,
    fontSize: 14,
  },
  heroCopy: {
    zIndex: 2,
    marginTop: 25,
  },
  greeting: {
    color: '#F8DCCC',
    fontFamily: fonts.medium,
    fontSize: 14,
    lineHeight: 19,
  },
  title: {
    marginTop: 5,
    color: '#FFFFFF',
    fontFamily: fonts.bold,
    fontSize: 28,
    lineHeight: 35,
    letterSpacing: -0.85,
  },
  subtitle: {
    marginTop: 3,
    color: '#FFE6D7',
    fontFamily: fonts.regular,
    fontSize: 13,
    lineHeight: 18,
  },
  illustration: {
    position: 'absolute',
    right: -29,
    bottom: -34,
    width: 178,
    height: 166,
    opacity: 0.78,
  },
  illustrationPlateOuter: {
    position: 'absolute',
    right: -9,
    bottom: 2,
    width: 131,
    height: 99,
    borderWidth: 1.2,
    borderColor: illustrationLine,
    borderRadius: 66,
    transform: [{ rotate: '8deg' }],
  },
  illustrationPlateInner: {
    position: 'absolute',
    right: 8,
    bottom: 17,
    width: 96,
    height: 68,
    borderWidth: 1.1,
    borderColor: illustrationLine,
    borderRadius: 49,
    transform: [{ rotate: '8deg' }],
  },
  illustrationFork: {
    position: 'absolute',
    left: 30,
    bottom: 23,
    width: 50,
    height: 112,
    transform: [{ rotate: '-37deg' }],
  },
  illustrationForkHandle: {
    position: 'absolute',
    left: 23,
    top: 28,
    width: 2,
    height: 87,
    borderRadius: 1,
    backgroundColor: illustrationLine,
  },
  illustrationForkTine: {
    position: 'absolute',
    top: 0,
    width: 1.3,
    height: 37,
    borderRadius: 1,
    backgroundColor: illustrationLine,
  },
  illustrationForkTineOne: { left: 13, transform: [{ rotate: '-5deg' }] },
  illustrationForkTineTwo: { left: 20 },
  illustrationForkTineThree: { left: 27 },
  illustrationForkTineFour: { left: 34, transform: [{ rotate: '5deg' }] },
  illustrationSprig: {
    position: 'absolute',
    right: 17,
    top: 0,
    width: 58,
    height: 92,
    transform: [{ rotate: '11deg' }],
  },
  illustrationStem: {
    position: 'absolute',
    left: 27,
    top: 6,
    width: 1.2,
    height: 89,
    borderRadius: 1,
    backgroundColor: illustrationLine,
    transform: [{ rotate: '7deg' }],
  },
  illustrationLeaf: {
    position: 'absolute',
    width: 21,
    height: 9,
    borderWidth: 1.1,
    borderColor: illustrationLine,
    borderRadius: 12,
  },
  illustrationLeafOne: { left: 5, top: 28, transform: [{ rotate: '34deg' }] },
  illustrationLeafTwo: { left: 28, top: 41, transform: [{ rotate: '-35deg' }] },
  illustrationLeafThree: { left: 4, top: 55, transform: [{ rotate: '39deg' }] },
  illustrationLeafFour: { left: 27, top: 67, transform: [{ rotate: '-38deg' }] },
  headerControls: {
    zIndex: 4,
    marginTop: -31,
    paddingHorizontal: 20,
  },
  searchBar: {
    height: 51,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    paddingHorizontal: 17,
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    shadowColor: '#5E3A2D',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.17,
    shadowRadius: 12,
    elevation: 7,
  },
  searchText: {
    flex: 1,
    color: '#766F6B',
    fontFamily: fonts.regular,
    fontSize: 14,
    lineHeight: 19,
  },
  quickActions: {
    flexDirection: 'row',
    gap: 13,
    marginTop: 16,
    paddingHorizontal: 3,
  },
  dashboard: {
    gap: 14,
    paddingHorizontal: 22,
    paddingTop: 18,
  },
  section: {
    gap: 6,
  },
  sectionHeader: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionTitle: {
    color: '#29221F',
    fontFamily: fonts.bold,
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: -0.35,
  },
  sectionAction: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingLeft: 8,
  },
  sectionActionText: {
    color: colors.olive,
    fontFamily: fonts.semiBold,
    fontSize: 12,
    lineHeight: 16,
  },
  groupGrid: {
    gap: 12,
  },
  activityList: {
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E2D7D1',
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
  },
  emptyCard: {
    minHeight: 84,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 13,
    borderWidth: 1,
    borderColor: '#E2D7D1',
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
  },
  emptyIcon: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: colors.primarySoft,
  },
  emptyCopy: {
    flex: 1,
    gap: 3,
  },
  emptyTitle: {
    color: colors.text,
    fontFamily: fonts.semiBold,
    fontSize: 13,
  },
  emptySubtitle: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 14,
  },
  loadingCard: {
    minHeight: 188,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginHorizontal: 22,
    marginTop: 22,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    backgroundColor: colors.surface,
    ...shadows.card,
  },
  loadingText: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 12,
  },
  errorCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginHorizontal: 22,
    marginTop: 22,
    padding: 15,
    borderWidth: 1,
    borderColor: '#F0C7BF',
    borderRadius: 18,
    backgroundColor: colors.dangerSoft,
  },
  errorIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: '#FBE2DD',
  },
  errorCopy: {
    flex: 1,
    gap: 5,
  },
  errorTitle: {
    color: colors.danger,
    fontFamily: fonts.semiBold,
    fontSize: 13,
  },
  errorText: {
    color: colors.mutedStrong,
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 15,
  },
  retryText: {
    marginTop: 3,
    color: colors.primary,
    fontFamily: fonts.semiBold,
    fontSize: 10,
  },
  pressed: {
    opacity: 0.78,
  },
});
