import { StyleSheet } from 'react-native';

import { colors } from '../theme/colors';

export const groupCardStyles = StyleSheet.create({
  card: {
    flex: 1,
    minWidth: 0,
    height: 130,
    overflow: 'hidden',
    borderRadius: 18,
    backgroundColor: '#D7CEC8',
  },
  image: { flex: 1, overflow: 'hidden', borderRadius: 18 },
  imageRadius: { borderRadius: 18 },
  overlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(30,22,18,0.34)',
  },
  fallbackIcon: { position: 'absolute', top: 38, right: 14 },
  privacyPill: {
    position: 'absolute',
    top: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.94)',
  },
  privacyText: { color: '#5C7842', fontSize: 7, fontWeight: '800' },
  bottomContent: {
    position: 'absolute',
    right: 9,
    bottom: 8,
    left: 9,
    gap: 3,
  },
  title: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: -0.15,
  },
  locationRow: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  locationText: { flex: 1, color: colors.white, fontSize: 8, fontWeight: '600' },
  avatarStack: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 1,
  },
  avatar: {
    width: 23,
    height: 23,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 1.25,
    borderColor: colors.white,
    borderRadius: 12,
    backgroundColor: '#F4DFD5',
  },
  avatarImage: { width: '100%', height: '100%' },
  avatarInitial: { color: colors.primary, fontSize: 8, fontWeight: '900' },
  avatarOverlap: { marginLeft: -6 },
  moreAvatar: {
    width: 23,
    height: 23,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.25,
    borderColor: colors.white,
    borderRadius: 12,
    backgroundColor: 'rgba(65,55,49,0.72)',
  },
  moreAvatarText: { color: colors.white, fontSize: 7, fontWeight: '900' },
  emptyAvatar: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
    borderWidth: 1.25,
    borderColor: colors.white,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  pressed: { opacity: 0.78 },
});
