import { StyleSheet } from 'react-native';

import { colors } from '../theme/colors';
import { fonts } from '../theme/fonts';
import { shadows } from '../theme/layout';

export const homeStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    flexGrow: 1,
    backgroundColor: colors.background,
  },
  header: {
    width: '100%',
  },
  heroBackground: {
    position: 'relative',
    overflow: 'hidden',
    paddingHorizontal: 24,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
  },
  topBar: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandLockup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  brandLogoFrame: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    padding: 2,
    borderRadius: 17,
    backgroundColor: '#FFF9F3',
  },
  brandLogo: {
    width: '100%',
    height: '100%',
  },
  brand: {
    color: '#FFF9F4',
    fontFamily: fonts.bold,
    fontSize: 18,
    lineHeight: 23,
    letterSpacing: 1.5,
  },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatarButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderRadius: 18,
    backgroundColor: '#FFF9F3',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarInitial: {
    color: '#C4492D',
    fontFamily: fonts.semiBold,
    fontSize: 14,
  },
  heroCopy: {
    zIndex: 2,
    maxWidth: 292,
    marginTop: 13,
  },
  greeting: {
    color: '#FFE8DC',
    fontFamily: fonts.semiBold,
    fontSize: 13,
    lineHeight: 18,
  },
  title: {
    marginTop: 6,
    color: '#FFFFFF',
    fontFamily: fonts.bold,
    fontSize: 25,
    lineHeight: 31,
    letterSpacing: -0.6,
  },
  subtitle: {
    marginTop: 2,
    color: '#FFE6D7',
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 17,
  },
  illustration: {
    position: 'absolute',
    right: -22,
    bottom: -39,
    width: 148,
    height: 148,
    opacity: 0.68,
  },
  headerControls: {
    zIndex: 4,
    marginTop: -26,
    paddingHorizontal: 22,
  },
  searchBar: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    paddingHorizontal: 18,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(217, 201, 192, 0.72)',
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    shadowColor: '#5E3A2D',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 5,
  },
  searchText: {
    flex: 1,
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 13,
    lineHeight: 18,
  },
  quickActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  dashboard: {
    gap: 22,
    paddingHorizontal: 22,
    paddingTop: 22,
  },
  section: {
    gap: 10,
  },
  sectionHeader: {
    minHeight: 26,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionTitle: {
    color: '#29221F',
    fontFamily: fonts.semiBold,
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.2,
  },
  sectionAction: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingLeft: 8,
  },
  sectionActionText: {
    color: colors.olive,
    fontFamily: fonts.semiBold,
    fontSize: 11,
    lineHeight: 15,
  },
  groupGrid: {
    gap: 12,
  },
  activityList: {
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    backgroundColor: colors.surfaceElevated,
  },
  emptyCard: {
    minHeight: 84,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 13,
    borderWidth: 1,
    borderColor: '#E2D7D1',
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
  },
  emptyIcon: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: colors.primarySoft,
  },
  emptyCopy: {
    flex: 1,
    gap: 3,
  },
  emptyTitle: {
    color: colors.text,
    fontFamily: fonts.semiBold,
    fontSize: 13,
  },
  emptySubtitle: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 14,
  },
  loadingCard: {
    minHeight: 188,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginHorizontal: 22,
    marginTop: 22,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    backgroundColor: colors.surface,
    ...shadows.card,
  },
  loadingText: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 12,
  },
  errorCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginHorizontal: 22,
    marginTop: 22,
    padding: 15,
    borderWidth: 1,
    borderColor: '#F0C7BF',
    borderRadius: 18,
    backgroundColor: colors.dangerSoft,
  },
  errorIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: '#FBE2DD',
  },
  errorCopy: {
    flex: 1,
    gap: 5,
  },
  errorTitle: {
    color: colors.danger,
    fontFamily: fonts.semiBold,
    fontSize: 13,
  },
  errorText: {
    color: colors.mutedStrong,
    fontFamily: fonts.regular,
    fontSize: 10,
    lineHeight: 15,
  },
  retryText: {
    marginTop: 3,
    color: colors.primary,
    fontFamily: fonts.semiBold,
    fontSize: 10,
  },
  pressed: {
    opacity: 0.78,
  },
});
