import { StyleSheet } from 'react-native';

export const refinedHomeStyles = StyleSheet.create({
  safeArea: { backgroundColor: '#FBF6F3' },
  content: {
    gap: 14,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 22,
    backgroundColor: '#FBF6F3',
  },
  brand: { fontSize: 27, letterSpacing: -0.8 },
  topActions: { gap: 8 },
  avatarButton: { width: 42, height: 42, borderRadius: 21 },
  hero: { gap: 4, marginTop: 2 },
  title: { fontSize: 25, letterSpacing: -0.7 },
  subtitle: { maxWidth: 300, fontSize: 11, lineHeight: 17 },
  searchBar: {
    minHeight: 46,
    gap: 9,
    paddingHorizontal: 15,
    borderColor: '#E4D8D0',
    borderRadius: 18,
    backgroundColor: '#FCF9F7',
  },
  searchText: { fontSize: 11 },
  quickActions: { gap: 8 },
  section: { gap: 9 },
  sectionHeader: { minHeight: 22, gap: 10 },
  sectionTitle: { fontSize: 14, letterSpacing: -0.15 },
  sectionAction: { gap: 3 },
  sectionActionText: { fontSize: 9 },
  groupGrid: { gap: 9 },
  activityList: {
    borderColor: '#E4D8D0',
    borderRadius: 17,
    backgroundColor: '#FCF9F7',
  },
  emptyCard: {
    minHeight: 68,
    gap: 10,
    padding: 11,
    borderColor: '#E4D8D0',
    borderRadius: 17,
    backgroundColor: '#FCF9F7',
  },
  emptyIcon: { width: 40, height: 40, borderRadius: 14 },
  emptyTitle: { fontSize: 11 },
  emptySubtitle: { fontSize: 8, lineHeight: 12 },
  loadingCard: {
    minHeight: 130,
    gap: 9,
    borderColor: '#E4D8D0',
    borderRadius: 19,
    backgroundColor: '#FCF9F7',
  },
  loadingText: { fontSize: 10 },
});
